@startuml


    package de.gematik.ti.cardreader.provider.usb.identos.entities {
      class IdentosCardReader {
          {static} - LOG : Logger
          {static} - PROTO_ID_T_1 : byte
          - cardReader : UsbReader
          - context : Context
          - initialized : boolean
          + IdentosCardReader()
          + initialize()
          + isInitialized()
          + connect()
          + connect()
          + getName()
          + isCardPresent()
          + waitForCardAbsent()
          + waitForCardPresent()
          + toString()
          + getReader()
          - initialize()
          - hasPermission()
          - registerForEvents()
          - checkInitialized()
      }
    }

  IdentosCardReader -up-|> ICardReader

@enduml
